<a href="https://colab.research.google.com/github/nick-otimo/Numpy/blob/main/Numpy_array_shape_%26_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Array Shaping
import numpy as np

arr_0d = np.array (21)
arr_1d = np.array ([21, 23, 43, 54, 56, 76, 14, 25, 47, 64, 71, 78])
arr_1d_test = np.array ([21, 23, 43, 54, 56, 76, 154], ndmin = 9)
arr_2d = np.array ([[23, 43, 52, 54], [12, 24, 36, 48], [76, 43, 54, 29]])
arr_3d = np.array ([[[21, 32, 42], [98, 45, 23], [32, 45, 78], [ 92, 93, 94], [54, 32, 16]]])

print (arr_1d_test.shape)
print (arr_2d.shape)
print (arr_3d.shape)
print (arr_1d.shape)

# Array Reshaping

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
# Array Reshaping 1D to 3D
newarr = arr_1d.reshape(2, 3, 2)

print(newarr)



# Unknown Dimension of an array
arr__ = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr__ = arr__.reshape(2, 2, -1)

print(newarr__)

# Flattening the arrays - Changing from multidimensional to 1D array
newarr___ = arr__.reshape(-1)

print(newarr___)




(1, 1, 1, 1, 1, 1, 1, 1, 7)
(3, 4)
(1, 5, 3)
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[21 23]
  [43 54]
  [56 76]]

 [[14 25]
  [47 64]
  [71 78]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
